### ISSUE TITLE
On auto-reconnect, existing subscriptions appear to persist, causing duplicate messages

### ISSUE THREAD

**Issue by mersiades** [stomp-js/stompjs#213] opened 2020-03-24 05:55 UTC
# Context
I'm making a messaging app using STOMP on the front-end (React.js) and back-end (Java Spring Boot), with the back-end hosted on Elastic Beanstalk with an Application Load Balancer.

The load balancer is disconnecting any websockets after 60 seconds of idle time. This is a known issue, the idea timeout can be extended to 4000 seconds, but it's not 100% relevant to this particular Github issue.

The issue lies in how the Client.onConnect() is working when it auto-reconnects. Even if there was no load balancer causing disconnections, there will be other causes of disconnections, hence this issue.

# Problem
What's been happening to me is that after a reconnect (after a 60 second idling disconnect), I started get duplicate messages sent and delivered. The number of duplicate messages equalling the number of times the websocket had been disconnected and reconnected.

What I think is happening is that the `.onConnect()` function, which subsequently calls `.subscribe()`, is creating new subscriptions which point to the same websocket destination as the previous subscription. Multiple websockets with the same destination = multiple messages sent and received.

It took me a while to figure out that this was going on because the subscription ids don't need to be unique... on each `.onConnect()`, subscriptions with exactly the same id as the previous subscription were being created. It wasn't until I added a `uuid` into the ids that I noticed that they were indeed different subscriptions to the same destination.  Here's an example of the two near-identical subscriptions receiving the same message:
![Screen Shot 2020-03-20 at 11 52 50 am](https://user-images.githubusercontent.com/6284016/77391850-db2c1f00-6ded-11ea-8583-77305e6d036f.png)

# Issue
So my question/issue is: What does this library do with the old subscriptions when reconnecting? Anything? Is there a way to clean them out?  Should there be?

I might have thought that when the websocket disconnects, those subscriptions automatically disappear too, but that doesn't appear to be happening in my case.

# Attempted Solutions
I've tried storing the subscriptions in a Redux store, and then calling `.unsubscribe` on them within the `.onconnect()` function, just prior to creating new subscriptions. This kind of worked, in that I'm not seeing duplicate messages anymore, but it's not actually unsubscribing anything. `.unsubscribe()` results in a `WebSocket is already in CLOSING or CLOSED state.` error, and the network tab in devtools shows that no UNSUBSCRIBE message is being sent to the server. Here's the code:

```
function connectStompClient() {
  const isLoggedIn = getLoggedIn();
  if (isLoggedIn) {
    const stompClient = new Client({
      brokerURL: wsDomainUrl + '/stompEndpoint',
      connectHeaders: { Authorization: authHeader() },
      debug: console.log,
      reconnectDelay: 2500,
      heartbeatIncoming: 10000,
      heartbeatOutgoing: 10000
    });

    // Creates new websockets if necessary
    let websocketsAreNotAvailableInTheBrowser = typeof WebSocket !== 'function';

    if (websocketsAreNotAvailableInTheBrowser) {
      stompClient.webSocketFactory = () => new SockJS(httpDomainUrl + '/stompEndpoint');
    }

    // Subscribes to websockets endpoints
    stompClient.onConnect = (frame) => {
      const chats: IChats = store.getState().chats.chats;

      // Gets all subscriptions form redux store and calls unsubscribe() on them
      unsubscribeAllWebsocketSubscriptions();
     
      // Clears the old subscriptions from redux store
      store.dispatch<any>(subscriptionActions.clearWebsocketSubscriptions());

      // Creates new subscriptions and sends them to Redux store
      subscribeToChats(stompClient, chats); 

      // Creates new subscriptions and sends them to Redux store
      subscribeToInvites(stompClient);
    };

    // Handles errors
    stompClient.onStompError = (frame: IFrame) => {
      console.log('Broker reported error: ' + frame.headers['message']);
      console.log('Additional details: ' + frame.body);
    };

    stompClient.activate();

    // Puts stomp client in the Redux store
    store.dispatch<any>(subscriptionActions.addClient(stompClient));
    return stompClient;
  }
}

export function unsubscribeAllWebsocketSubscriptions() {
  const subscriptions = store.getState().subscriptions.websocketSubscriptions;
  subscriptions.map((sub) => sub.unsubscribe());
}

```

Another solution that I'm working on is a "keep-alive" heart-beat, which will go a long way to reducing the severity of this problem. But I still need to be able to have websocket disconnections and reconnections that don't result in duplicate subscriptions and thus duplicate messages.

**Comment by kum-deepak** [comment] 2020-03-24 08:34
Thanks for the detailed report. Rarely issues are filed with so much diligence.

I know of one scenario where it might happen. If this library believes, typically when heartbeat is not received, that the underlying connection is lost, it tries first to close the connection. Here we go totally on the browser that how long will it take to actually drop the underlying connection (I have seen more than 60 seconds sometimes) indicated by `WebSocket is already in CLOSING or CLOSED state`. Usually the connection has actually been lost by this phase. However, if for some reason, the connection was still active we would continue to receive messages.

One approach I can see that before issuing `.close` on the underlying websocket the `onmessage` can be set to a no-op. This should ignore all the messages received on the socket.

I wish the standards supported a method to just close the connection immediately.

**Comment by kum-deepak** [comment] 2020-03-24 13:11
Just now released 5.4.4 please check if your issue gets resolved. Thanks!

**Comment by tedhopps** [comment] 2020-03-24 15:22
@kum-deepak The issue is that @mersiades is not issuing the `.close` call. The load balancer terminates the socket connection. On a reconnect the subscription is dead unless you call the `subscribe` method again. However, now the `subscribe` callback will be called twice for each subscription message, on the next reconnect `subscribe` the subscribe callback will be called three times etc. The disconnect does not clean up the subscribe callback and when you resubscribe the callback is duplicated. Do you think this is possible?

**Comment by mersiades** [comment] 2020-03-25 02:42
Well folks, mea culpa, my bad.

It turns out that I had an extra call to `connectStompClient()` at one point in my code, which created a second websocket. So I'd have two sets of websocket+subscriptions after each auto-reconnect.

Thanks for your replies and help. And thanks for all your work on this library.

**Closed** 2020-03-25 03:55 UTC
