### ISSUE TITLE
How to ignore the error 'ERR_CERT_COMMON_NAME_INVALID' 

### ISSUE THREAD

**Issue by caozhaohong** [stomp-js/stompjs#272] opened 2020-09-04 03:12 UTC
Please see FAQs at https://stomp-js.github.io/faqs/2019/05/20/faqs.html before reporting.

My question is base on following issue:
https://github.com/stomp-js/stompjs/issues/271

In browser, in case 'ERR_CERT_COMMON_NAME_INVALID'  prompted, user can clike 'ignore the warning and continue the connection.'

On stom-js, how to ignore the 'ERR_CERT_COMMON_NAME_INVALID'  and go on?

**Comment by kum-deepak** [comment] 2020-09-04 03:30
Duplicate of #271.

**Closed by kum-deepak** 2020-09-04 03:30 UTC
